<?php

namespace IHdigital\Facebook\Token;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-11 at 08:37:13.
 */
class FacebookTokenTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var FacebookToken
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FacebookToken("234855093568583", "cadf904653c5f8b6bec08591e25260df", "http://ads.iris365.com/", "EAADVmXZAtBEcBAIxUy6J9es9YzUo5gjRIZAlWpDP3wCTEKcptKDexUd3kKwc6fWeOHdZAlVx0ZAADe6mEL6niR5p5lZB5Pj8WW1Yt0tyYcYOZB0wUaJpFpp9UOOR2gPcZBPJDZCPcWWzi3gOsZBYqs5D474jLetwOZC0sZD");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers IHdigital\Facebook\Token\FacebookToken::getCode
     * @todo   Implement testGetCode().
     */
    public function testGetCode() {
        $code = $this->object->getCode();
        $this->assertObjectHasAttribute("code", $code);
        return $code;
    }

    /**
     * @covers IHdigital\Facebook\Token\FacebookToken::getLongAccessToken
     * @todo   Implement testGetLongAccessToken().
     * @depends testGetCode
     */
    public function testGetLongAccessToken($code) {
        $token = $this->object->getLongAccessToken($code);

        $this->assertObjectHasAttribute("access_token", $token);
        return $token;
    }

    /**
     * @covers IHdigital\Facebook\Token\FacebookToken::makeAsPermanentAccessToken
     * @todo   Implement testMakeAsPermanentAccessToken().
     * @depends testGetLongAccessToken
     */
    public function testMakeAsPermanentAccessToken($token) {

        $this->assertNotEmpty($this->object->makeAsPermanentAccessToken($token)->data);
    }

}
